
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/user3/code/CSE599K_SP25_Code/.venv/lib/python3.10/site-packages/cmake/data/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:3 (project)"
    message: |
      The system is: Linux - 5.15.0-113-generic - x86_64
  -
    kind: "message-v1"
    backtrace:
      - "/home/user3/code/CSE599K_SP25_Code/.venv/lib/python3.10/site-packages/cmake/data/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/home/user3/code/CSE599K_SP25_Code/.venv/lib/python3.10/site-packages/cmake/data/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/home/user3/code/CSE599K_SP25_Code/.venv/lib/python3.10/site-packages/cmake/data/share/cmake-3.31/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: /usr/bin/c++ 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "a.out"
      
      The CXX compiler identification is GNU, found in:
        /home/user3/deeksha/assignment1/silu/CUDA/CMakeFiles/3.31.4/CompilerIdCXX/a.out
      
  -
    kind: "message-v1"
    backtrace:
      - "/home/user3/code/CSE599K_SP25_Code/.venv/lib/python3.10/site-packages/cmake/data/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:1250 (message)"
      - "/home/user3/code/CSE599K_SP25_Code/.venv/lib/python3.10/site-packages/cmake/data/share/cmake-3.31/Modules/CMakeDetermineCUDACompiler.cmake:75 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Checking whether the CUDA compiler is NVIDIA using "" did not match "nvcc: NVIDIA \\(R\\) Cuda compiler driver":
  -
    kind: "message-v1"
    backtrace:
      - "/home/user3/code/CSE599K_SP25_Code/.venv/lib/python3.10/site-packages/cmake/data/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:1250 (message)"
      - "/home/user3/code/CSE599K_SP25_Code/.venv/lib/python3.10/site-packages/cmake/data/share/cmake-3.31/Modules/CMakeDetermineCUDACompiler.cmake:75 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Checking whether the CUDA compiler is Clang using "" did not match "(clang version)":
  -
    kind: "message-v1"
    backtrace:
      - "/home/user3/code/CSE599K_SP25_Code/.venv/lib/python3.10/site-packages/cmake/data/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/home/user3/code/CSE599K_SP25_Code/.venv/lib/python3.10/site-packages/cmake/data/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/home/user3/code/CSE599K_SP25_Code/.venv/lib/python3.10/site-packages/cmake/data/share/cmake-3.31/Modules/CMakeDetermineCUDACompiler.cmake:131 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the CUDA compiler identification source file "CMakeCUDACompilerId.cu" failed.
      Compiler: CMAKE_CUDA_COMPILER-NOTFOUND 
      Build flags: 
      Id flags:  -v
      
      The output was:
      no such file or directory
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/home/user3/code/CSE599K_SP25_Code/.venv/lib/python3.10/site-packages/cmake/data/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/home/user3/code/CSE599K_SP25_Code/.venv/lib/python3.10/site-packages/cmake/data/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/home/user3/code/CSE599K_SP25_Code/.venv/lib/python3.10/site-packages/cmake/data/share/cmake-3.31/Modules/CMakeDetermineCUDACompiler.cmake:131 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the CUDA compiler identification source file "CMakeCUDACompilerId.cu" failed.
      Compiler: CMAKE_CUDA_COMPILER-NOTFOUND 
      Build flags: 
      Id flags:  -v
      
      The output was:
      no such file or directory
      
      
...

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/user3/code/CSE599K_SP25_Code/.venv/lib/python3.10/site-packages/cmake/data/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:1237 (message)"
      - "/home/user3/code/CSE599K_SP25_Code/.venv/lib/python3.10/site-packages/cmake/data/share/cmake-3.31/Modules/CMakeDetermineCUDACompiler.cmake:75 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Checking whether the CUDA compiler is NVIDIA using "" matched "nvcc: NVIDIA \\(R\\) Cuda compiler driver":
      nvcc: NVIDIA (R) Cuda compiler driver
      Copyright (c) 2005-2025 NVIDIA Corporation
      Built on Fri_Feb_21_20:23:50_PST_2025
      Cuda compilation tools, release 12.8, V12.8.93
      Build cuda_12.8.r12.8/compiler.35583870_0
...
